name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5

jobs:
  mac_workflow:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        run: |
          brew install perl
          echo "/Users/runner/perl5/bin" >> $GITHUB_PATH
          mkdir -p ~/bin
          cd ~/bin
          curl -L https://cpanmin.us/ -o cpanm
          chmod +x cpanm
          echo "~/bin" >> $GITHUB_PATH
          which perl
          which cpanm

      #  some painful steps here that will hopefully be backed out at some point
      - name: Install GDAL and its deps
        run: |
          brew update
          # brew unlink pkg-config@0.29.2
          brew install pkgconf
          brew link --overwrite pkgconf
          brew install gdal
          # brew install --force --overwrite gdal
        
      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          echo '20241125' >> perlversion.txt
          ls -l perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v4
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install Dynamic Dependencies
        run: |
          cpanm --notest local::lib
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          cpanm --notest Alien::Build  
          cpanm --installdeps --notest Alien::sqlite
          cpanm -v Alien::sqlite
          cpanm --installdeps --notest Alien::libtiff
          cpanm -v Alien::libtiff
          cpanm --installdeps --notest Alien::geos::af
          cpanm -v Alien::geos::af
          cpanm --installdeps --notest Alien::proj
          cpanm -v Alien::proj
          cpanm --installdeps --notest Alien::gdal
          cpanm -v Alien::gdal
          cpanm --notest --installdeps --no-man-pages PDL
          cpanm --notest --no-man-pages PDL
          cpanm --notest https://github.com/shawnlaffan/biodiverse.git
          cpanm --notest Excel::ValueReader::XLSX
          cd inst/perl
          cpanm --notest --installdeps .
          cd -
      
      - name: Run Perl Tests
        run: |
          cd inst/perl
          prove -l -j4 t
          cd -
      
      - name: Upload mojo logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mojo-files
          path: /home/runner/BiodiverseR/logs/*.txt
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Run R Tests
        run: |
          Rscript --no-save tests/testthat.R
